### ISSUE TITLE
ulid4s fails on Windows Systems 

### ISSUE THREAD

**Issue by uneewk** [petitviolet/ulid4s#4]
Problem:

ulid4s fails to generate a ULID on the windows platform. Running the following scala commands on a Windows System results in the exception below:

```
import net.petitviolet.ulid4s.ULID
ULID.generate
```

Exception:
```
java.security.NoSuchAlgorithmException: NativePRNGNonBlocking SecureRandom not available
at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
at java.security.SecureRandom.getInstance(SecureRandom.java:288)
at net.petitviolet.ulid4s.ULID$.<init>(ULID.scala:9)
at net.petitviolet.ulid4s.ULID$.<clinit>(ULID.scala)
... 40 elided
```

Is there a workaround that you know of that will allow me to continue to use this library on Windows?

**Comment by petitviolet** [comment]
@uneewk Sorry for late reply. I assume https://github.com/petitviolet/ulid4s/pull/1 fixed the issue you reported. Could you try it with the latest version?
